spring.application.name=EmployeApplication
server.port=8080

#database

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:~/course-employee-application
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.username=sa
spring.datasource.password=
